package Calculator;

public class Main {

    public static void main(String[] args) {
	// write your code here
        System.out.println("tests for Polynomial");
        Polynomial ans= Polynomial.build("1 2 3");
        System.out.println(ans.toString());
        Polynomial ans1= Polynomial.build("0 1 2 3");
        System.out.println(ans1.toString());
        Polynomial ans2= Polynomial.build("0 0 0 0 0 0 7");
        System.out.println(ans2.toString());
        Polynomial ans3= Polynomial.build("5");
        System.out.println(ans3.toString());
        Polynomial ans4= Polynomial.build("1 -2 3");
        System.out.println(ans4.toString());
        Polynomial ans5= Polynomial.build("0 1/2 3 -5/3");
        System.out.println(ans5.toString());
//        System.out.println("tests for integer");
//        System.out.println("integer");
//        Integer c4 = new Integer(4);
//        Integer c5 = new Integer(5);
//        Integer cm3 = new Integer(-3);
//        Integer cm2 = new Integer(-2);
//        Integer cz = new Integer(0);
//        System.out.println("4: "+c4.getNumber());
//        System.out.println("-2: "+cm2.getNumber());
//        System.out.println("0: "+ cz.getNumber());
//        System.out.println("0: "+ cz.toString());
//        System.out.println("5: "+ c5.toString());
//        System.out.println("-3: "+ cm3.toString());
//        System.out.println("2: "+ c5.add(cm3));
//        System.out.println("9: "+ c5.add(c4));
//        System.out.println("-2: "+ cm2.add(cz));
//        System.out.println("-15: "+ c5.mul(cm3));
//        System.out.println("20: "+ c5.mul(c4));
//        System.out.println("0: "+ cm2.mul(cz));
//        System.out.println("2: "+ cm2.neg());
//        System.out.println("0: "+ cz.neg());
//        System.out.println("-5: "+ c5.neg());
//        System.out.println("16: "+ cm2.power(c4.getNumber()));
//        System.out.println("0: "+ cz.power(c5.getNumber()));
//        System.out.println("4^5: "+ c4.power(c5.getNumber()));
//        System.out.println("1/25: "+ c5.power(cm3.getNumber()));
//        System.out.println("-1: "+ cm2.sign());
//        System.out.println("0: "+ cz.sign());
//        System.out.println("1: "+ c5.sign());
//        System.out.println("tests for rational");
//        Rational c1_4 = new Rational(1,4);
//        Rational c2_5 = new Rational(2,5);
//        Rational c3_m4 = new Rational(3,-4);
//        Rational cm2_7 = new Rational(-2,7);
//        Rational cm2_6 = new Rational(-2,6);
//        Rational c2_4 = new Rational(2,4);
//        Rational c_z = new Rational(0,0);
//        Rational cm2_m7 = new Rational(-2,-7);
//        System.out.println("getters");
//        System.out.println("1: "+c1_4.getNumerator());
//        System.out.println("2: "+c2_5.getNumerator());
//        System.out.println("-4: "+ c3_m4.getDenominator());
//        System.out.println("-2: "+cm2_7.getNumerator());
//        System.out.println("7: "+cm2_7.getDenominator());
//        System.out.println("0: "+ c_z.getNumerator());
//        System.out.println("0: "+ c_z.getDenominator());
//        System.out.println("to string");
//        System.out.println("1/4: "+ c1_4.toString());
//        System.out.println("2/5: "+ c2_5.toString());
//        System.out.println("-3/4: "+ c3_m4.toString());
//        System.out.println("-2/7: "+ cm2_7.toString());
//        System.out.println("reduce");
//        System.out.println("1/2: "+ c2_4.reduce());
//        System.out.println("2/5: "+ c2_5.reduce());
//        System.out.println("1/3: "+ cm2_6.reduce());
//        System.out.println("2/7: "+ cm2_m7.reduce());
//        System.out.println("arithmetic");
//        System.out.println("0.25+0.4: "+ c1_4.add(c2_5));
//        System.out.println("-1/2: "+ c3_m4.add(c1_4));
//        System.out.println("4/42: "+ cm2_7.mul(cm2_6));
//        System.out.println("5.25: "+ c5.add(c1_4));
//        System.out.println("neg");
//        System.out.println("-1/4: "+ c1_4.neg());
//        System.out.println("3/4: "+ c3_m4.neg());
//        System.out.println("2/7: "+ cm2_7.neg());
//        System.out.println("power");
//        System.out.println("1/256: "+ c1_4.power(4));
//        System.out.println("9/16: "+ c3_m4.power(2));
//        System.out.println("8/125: "+ c2_5.power(3));
//        System.out.println("sign");
//        System.out.println("1: "+ c1_4.sign());
//        System.out.println("-1: "+ c3_m4.sign());
//        System.out.println("0: "+ c_z.sign());
//        System.out.println("tests for monomial");
//        Monomial m25 = new Monomial(5,cm2);
//        Monomial four_four= new Monomial(4,c4);
//        Monomial five_three = new Monomial(3,c5);
//        Monomial mthree_two = new Monomial(2,cm3);
//        Monomial zero_three = new Monomial(3, cz);
//        Monomial four_two= new Monomial(2,c4);
//        Monomial five_zero= new Monomial(0,c5);
//        Monomial mtwo_mtwo = new Monomial(-2,cm2);
//        System.out.println("arithmetic");
//        System.out.println("-: "+ m25.add(five_three));
//        System.out.println("-: "+ mthree_two.add(five_zero));
//        System.out.println("5^3: "+ five_three.add(zero_three));
//        System.out.println("1^2: "+ mthree_two.add(four_two));
//        System.out.println("-10^15: "+ m25.mul(five_three));
//        System.out.println("-3: "+ mthree_two.mul(five_zero));
//        System.out.println("0: "+ five_three.mul(zero_three));
//        System.out.println("-12^4: "+ mthree_two.mul(four_two));
    }
}
